package coronaprojekt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author mizz_
 */
public class BjudInGrupp extends javax.swing.JFrame {

    
    
    
    private static InfDB minDatabaskoppling;
    /**
     * Creates new form BjudInGrupp
     */
    public BjudInGrupp(InfDB minDatabaskoppling) {
     
        initComponents();
        this.minDatabaskoppling = minDatabaskoppling;
        fyllCbProjekt();
        fyllCbPerson();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projektCb = new javax.swing.JComboBox<>();
        personCb = new javax.swing.JComboBox<>();
        bjudJb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bjudJb.setText("Bjud in ");
        bjudJb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bjudJb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjudJbActionPerformed(evt);
            }
        });

        jLabel1.setText("Välj person:");

        jLabel2.setText("Välj projekt:");

        jLabel4.setText("Bjud in till befintligt projekt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projektCb, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personCb, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(bjudJb, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projektCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(bjudJb)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bjudJbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjudJbActionPerformed


        String projekt = projektCb.getSelectedItem().toString();
        String anvandare = personCb.getSelectedItem().toString();
        
        String ANVANDAREID = "SELECT ID FROM ANVANDARE WHERE ANVANDARNAMN = '" + anvandare + "'";
        String projektID = "SELECT ID FROM FORSKNINGSPROJEKT WHERE PROJEKT = '" + projekt + "'";

          try{
        this.minDatabaskoppling.insert("INSERT INTO PROJEKT VALUES (" + ANVANDAREID + ", " + projektID + ")");
        JOptionPane.showMessageDialog(null, "Anvandaren är inbjuden!");
        }
        catch(InfException e){
        JOptionPane.showMessageDialog(null, "Error!!!");
        }







        // TODO add your handling code here:
    }//GEN-LAST:event_bjudJbActionPerformed

    
   private void fyllCbProjekt()
    {
    String fraga = "SELECT NAMN FROM FORSKNINGSPROJEKT";
    
    ArrayList<String> allaProjekt;
    
    try
    {
    allaProjekt = minDatabaskoppling.fetchColumn(fraga);
    
    
     if (!(allaProjekt == null)){
    for(String projekt: allaProjekt){
    projektCb.addItem(projekt);
    }
    }
     else{
     JOptionPane.showMessageDialog(null,"Det finns inga projekt registrerade");
     }
    }
    catch(InfException e)
    {
    JOptionPane.showMessageDialog(null,"Fel med databasuppkopplingen"); 
    }
    catch(Exception e)
    {
    JOptionPane.showMessageDialog(null,"Något gick fel!");
    System.out.println(e);
    
    }
    
    } 
    
    
    private void fyllCbPerson()
    {
    String fraga = "SELECT ANVANDARNAMN FROM ANVANDARE";
    
    ArrayList<String> allaAnvand;
    
    try
    {
    allaAnvand = minDatabaskoppling.fetchColumn(fraga);
    
    
     if (!(allaAnvand == null)){
    for(String anvandaren: allaAnvand){
    personCb.addItem(anvandaren);
    }
    }
     else{
     JOptionPane.showMessageDialog(null,"Det finns inga anvandare registrerade");
     }
    }
    catch(InfException e)
    {
    JOptionPane.showMessageDialog(null,"Fel med databasuppkopplingen"); 
    }
    catch(Exception e)
    {
    JOptionPane.showMessageDialog(null,"Något gick fel!");
    System.out.println(e);
    
    }
    
    } 
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BjudInGrupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BjudInGrupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BjudInGrupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BjudInGrupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BjudInGrupp(minDatabaskoppling).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bjudJb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> personCb;
    private javax.swing.JComboBox<String> projektCb;
    // End of variables declaration//GEN-END:variables
}
