/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronaprojekt;

import java.awt.Color;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Simon Sandberg
 */
public class Login_Page extends javax.swing.JFrame {

    public static InfDB minDatabaskoppling;
    private static String currentUserName;
    private boolean admin;

    /**
     * Creates new form Login_Page
     */
    public Login_Page(InfDB minDatabaskoppling) {
        initComponents();
        initLoginScreen();
        this.minDatabaskoppling = minDatabaskoppling;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anv_Txt_Fld = new javax.swing.JTextField();
        anv_Pass_Fld = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JPanel();
        login_Btn_Lbl = new javax.swing.JLabel();
        background_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(480, 360));
        setMinimumSize(new java.awt.Dimension(480, 360));
        setPreferredSize(new java.awt.Dimension(480, 360));
        setSize(new java.awt.Dimension(480, 360));
        getContentPane().setLayout(null);

        anv_Txt_Fld.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        getContentPane().add(anv_Txt_Fld);
        anv_Txt_Fld.setBounds(160, 80, 160, 40);

        anv_Pass_Fld.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        getContentPane().add(anv_Pass_Fld);
        anv_Pass_Fld.setBounds(160, 140, 160, 40);

        login_btn.setForeground(new java.awt.Color(255, 255, 255));
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                login_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                login_btnMouseReleased(evt);
            }
        });
        login_btn.setLayout(new java.awt.BorderLayout());

        login_Btn_Lbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        login_Btn_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        login_Btn_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_Btn_Lbl.setText("Login");
        login_btn.add(login_Btn_Lbl, java.awt.BorderLayout.CENTER);

        getContentPane().add(login_btn);
        login_btn.setBounds(160, 220, 160, 50);

        background_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coronaprojekt/resources/Login_Screen_Background.jpg"))); // NOI18N
        getContentPane().add(background_Image);
        background_Image.setBounds(0, 0, 480, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseEntered
        login_btn.setBackground(hoverColorBtn);
        login_btn.setVisible(false);
        login_btn.setVisible(true);
    }//GEN-LAST:event_login_btnMouseEntered

    private void login_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseExited
        login_btn.setBackground(baseColorBtn);
        login_btn.setVisible(false);
        login_btn.setVisible(true);
    }//GEN-LAST:event_login_btnMouseExited

    private void login_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMousePressed
        login_btn.setBackground(clickedColorBtn);
        login_btn.setVisible(false);
        login_btn.setVisible(true);
    }//GEN-LAST:event_login_btnMousePressed

    private void login_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseReleased
        login_btn.setBackground(hoverColorBtn);
        login_btn.setVisible(false);
        login_btn.setVisible(true);
    }//GEN-LAST:event_login_btnMouseReleased

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
        try {
            String anvandarnamn = anv_Txt_Fld.getText();
            String losenord = anv_Pass_Fld.getText();
            String hittaAnvandarnamn = "select Anvandarnamn from Anvandare where Anvandarnamn ='" + anvandarnamn + "';";
            String resultat = minDatabaskoppling.fetchSingle(hittaAnvandarnamn);
            if (resultat != null) {
                String sql1 = "select Losenord from Anvandare where Anvandarnamn ='" + anvandarnamn + "';";
                String result1 = minDatabaskoppling.fetchSingle(sql1);
                String sql2 = "select IsAdmin from Anvandare where Anvandarnamn ='" + anvandarnamn + "'";
                String inloggadAdmin = minDatabaskoppling.fetchSingle(sql2);
                setCurrentUserName(anvandarnamn);
                if (result1.equals(losenord) && inloggadAdmin.equals("J")) {

                    this.setVisible(false);
                    new Main_Page(minDatabaskoppling).setVisible(true);

                    admin = true;
                } else if (result1.equals(losenord)) {
                    admin = false;
                    this.setVisible(false);
                    new Main_Page(minDatabaskoppling).setVisible(true);

                } else {
                    System.out.println("Ogiltigt lösenord");
                    JOptionPane.showMessageDialog(null, "Ogiltigt lösenord");
                }
            } else {
                System.out.println("Ogiltigt användarnamn");
                JOptionPane.showMessageDialog(null, "Ogiltigt användarnamn");
            }
        } catch (InfException undantag) {
            System.out.println("Fel: " + undantag.getMessage());
        }
    }//GEN-LAST:event_login_btnMouseClicked

    public String getCurrentUserName() {
        return this.currentUserName;
    }

    public void setCurrentUserName(String userName) {
        this.currentUserName = userName;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page(minDatabaskoppling).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField anv_Pass_Fld;
    private javax.swing.JTextField anv_Txt_Fld;
    private javax.swing.JLabel background_Image;
    private javax.swing.JLabel login_Btn_Lbl;
    private javax.swing.JPanel login_btn;
    // End of variables declaration//GEN-END:variables

    private Color hoverColorBtn = new Color(41, 205, 255, 200);
    private Color baseColorBtn = new Color(3, 194, 252, 150);
    private Color clickedColorBtn = new Color(117, 223, 255, 200);
    private Color baseColorSolidBtn = new Color(0, 157, 204);

    public void initLoginScreen() {
        setLocationRelativeTo(null);

        anv_Txt_Fld.setBackground(baseColorSolidBtn);

        anv_Pass_Fld.setBackground(baseColorSolidBtn);

        login_btn.setBackground(baseColorBtn);

        System.out.println("Init of Login Screen Complete");
    }
}
