/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronaprojekt;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import oru.inf.InfDB;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import java.lang.IllegalArgumentException;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

import javax.swing.*; 
import java.awt.event.*;
/**
 *
 * @author Simon Sandberg
 */
public class Main_page_jacob extends javax.swing.JFrame {
    public static InfDB minDatabaskoppling;
    public static int anvandareID;
    /**
     * Creates new form Main_Page
     */
    public Main_page_jacob(InfDB minDatabaskoppling, int anvandareID) {
        initComponents();
        initMainWindow();
                this.minDatabaskoppling = minDatabaskoppling; 
                this.anvandareID = anvandareID;
                
                try{
                   String fraga = "SELECT NAMN FROM KATEGORI";
                    ArrayList<HashMap<String, String>> resultat = minDatabaskoppling.fetchRows(fraga); 
                    
                    for(int i=0; i<resultat.size(); i++){
                        
                    }
                    
                }catch(InfException e){
                    
                }
                
                
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        formel_Blogg_btn = new javax.swing.JPanel();
        formBlg_Lbl = new javax.swing.JLabel();
        informell_Blogg_btn = new javax.swing.JPanel();
        informBlg_Lbl = new javax.swing.JLabel();
        projects_btn = new javax.swing.JPanel();
        projBtn_Lbl = new javax.swing.JLabel();
        newsflow_Panel = new javax.swing.JPanel();
        notis_btn = new javax.swing.JPanel();
        notis_lbl = new javax.swing.JLabel();
        account_btn = new javax.swing.JPanel();
        account_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main_Window_Pane");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setName("main_Page_JFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        formel_Blogg_btn.setBackground(new java.awt.Color(3, 194, 252));
        formel_Blogg_btn.setPreferredSize(new java.awt.Dimension(480, 100));
        formel_Blogg_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formel_Blogg_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formel_Blogg_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formel_Blogg_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formel_Blogg_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formel_Blogg_btnMouseReleased(evt);
            }
        });
        formel_Blogg_btn.setLayout(new java.awt.BorderLayout());

        formBlg_Lbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        formBlg_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        formBlg_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formBlg_Lbl.setText("Formel Blogg");
        formBlg_Lbl.setMaximumSize(new java.awt.Dimension(300, 25));
        formBlg_Lbl.setPreferredSize(new java.awt.Dimension(300, 25));
        formBlg_Lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formBlg_LblMouseClicked(evt);
            }
        });
        formel_Blogg_btn.add(formBlg_Lbl, java.awt.BorderLayout.CENTER);

        getContentPane().add(formel_Blogg_btn);
        formel_Blogg_btn.setBounds(6, 6, 480, 100);

        informell_Blogg_btn.setBackground(new java.awt.Color(3, 194, 252));
        informell_Blogg_btn.setPreferredSize(new java.awt.Dimension(480, 100));
        informell_Blogg_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informell_Blogg_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informell_Blogg_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                informell_Blogg_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                informell_Blogg_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                informell_Blogg_btnMouseReleased(evt);
            }
        });
        informell_Blogg_btn.setLayout(new java.awt.BorderLayout());

        informBlg_Lbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        informBlg_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        informBlg_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informBlg_Lbl.setText("Informell Blogg");
        informBlg_Lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informBlg_LblMouseClicked(evt);
            }
        });
        informell_Blogg_btn.add(informBlg_Lbl, java.awt.BorderLayout.CENTER);

        getContentPane().add(informell_Blogg_btn);
        informell_Blogg_btn.setBounds(492, 6, 480, 100);

        projects_btn.setBackground(new java.awt.Color(3, 194, 252));
        projects_btn.setPreferredSize(new java.awt.Dimension(480, 100));
        projects_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projects_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projects_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projects_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                projects_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                projects_btnMouseReleased(evt);
            }
        });
        projects_btn.setLayout(new java.awt.BorderLayout());

        projBtn_Lbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        projBtn_Lbl.setForeground(new java.awt.Color(255, 255, 255));
        projBtn_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projBtn_Lbl.setText("Projekt");
        projBtn_Lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projBtn_LblMouseClicked(evt);
            }
        });
        projects_btn.add(projBtn_Lbl, java.awt.BorderLayout.CENTER);

        getContentPane().add(projects_btn);
        projects_btn.setBounds(978, 6, 480, 100);

        newsflow_Panel.setBackground(new java.awt.Color(3, 194, 252));

        javax.swing.GroupLayout newsflow_PanelLayout = new javax.swing.GroupLayout(newsflow_Panel);
        newsflow_Panel.setLayout(newsflow_PanelLayout);
        newsflow_PanelLayout.setHorizontalGroup(
            newsflow_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        newsflow_PanelLayout.setVerticalGroup(
            newsflow_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );

        getContentPane().add(newsflow_Panel);
        newsflow_Panel.setBounds(1470, 110, 445, 980);

        notis_btn.setBackground(new java.awt.Color(3, 194, 252));
        notis_btn.setForeground(new java.awt.Color(255, 255, 255));
        notis_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notis_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notis_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notis_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                notis_btnMouseReleased(evt);
            }
        });
        notis_btn.setLayout(new java.awt.BorderLayout());

        notis_lbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        notis_lbl.setForeground(new java.awt.Color(255, 255, 255));
        notis_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notis_lbl.setText("Notiser");
        notis_btn.add(notis_lbl, java.awt.BorderLayout.CENTER);

        getContentPane().add(notis_btn);
        notis_btn.setBounds(1470, 5, 220, 100);

        account_btn.setBackground(new java.awt.Color(3, 194, 252));
        account_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                account_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                account_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                account_btnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                account_btnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                account_btnMouseReleased(evt);
            }
        });
        account_btn.setLayout(new java.awt.BorderLayout());

        account_lbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        account_lbl.setForeground(new java.awt.Color(255, 255, 255));
        account_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account_lbl.setText("Konto");
        account_btn.add(account_lbl, java.awt.BorderLayout.CENTER);

        getContentPane().add(account_btn);
        account_btn.setBounds(1695, 5, 220, 100);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 170, 1440, 740);

        jButton1.setText("Min Wall");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 120, 240, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 120, 220, 20);

        pack();
    }// </editor-fold>                        
    //Funktioner som hanterar hur UI regerar när användaren rör sin mus över och klickar på delar av UI
    private void formel_Blogg_btnMouseEntered(java.awt.event.MouseEvent evt) {                                              
        formel_Blogg_btn.setBackground(hoverColorBtn);
        formel_Blogg_btn.setVisible(false);
        formel_Blogg_btn.setVisible(true);
    }                                             

    private void formel_Blogg_btnMouseExited(java.awt.event.MouseEvent evt) {                                             
        formel_Blogg_btn.setBackground(baseColorBtn);
        formel_Blogg_btn.setVisible(false);
        formel_Blogg_btn.setVisible(true);
    }                                            

    private void informell_Blogg_btnMouseEntered(java.awt.event.MouseEvent evt) {                                                 
        informell_Blogg_btn.setBackground(hoverColorBtn);
        informell_Blogg_btn.setVisible(false);
        informell_Blogg_btn.setVisible(true);       
    }                                                

    private void informell_Blogg_btnMouseExited(java.awt.event.MouseEvent evt) {                                                
        informell_Blogg_btn.setBackground(baseColorBtn);
        informell_Blogg_btn.setVisible(false);
        informell_Blogg_btn.setVisible(true);
    }                                               

    private void projects_btnMouseEntered(java.awt.event.MouseEvent evt) {                                          
        projects_btn.setBackground(hoverColorBtn);
        projects_btn.setVisible(false);
        projects_btn.setVisible(true);
    }                                         

    private void projects_btnMouseExited(java.awt.event.MouseEvent evt) {                                         
        projects_btn.setBackground(baseColorBtn);
        projects_btn.setVisible(false);
        projects_btn.setVisible(true);
    }                                        

    private void notis_btnMouseEntered(java.awt.event.MouseEvent evt) {                                       
        notis_btn.setBackground(hoverColorBtn);
        notis_btn.setVisible(false);
        notis_btn.setVisible(true);
    }                                      

    private void notis_btnMouseExited(java.awt.event.MouseEvent evt) {                                      
        notis_btn.setBackground(baseColorBtn);
        notis_btn.setVisible(false);
        notis_btn.setVisible(true);
    }                                     

    private void account_btnMouseEntered(java.awt.event.MouseEvent evt) {                                         
        account_btn.setBackground(hoverColorBtn);
        account_btn.setVisible(false);
        account_btn.setVisible(true);
    }                                        

    private void account_btnMouseExited(java.awt.event.MouseEvent evt) {                                        
        account_btn.setBackground(baseColorBtn);
        account_btn.setVisible(false);
        account_btn.setVisible(true);
    }                                       

    private void formel_Blogg_btnMouseReleased(java.awt.event.MouseEvent evt) {                                               
        formel_Blogg_btn.setBackground(hoverColorBtn);
        formel_Blogg_btn.setVisible(false);
        formel_Blogg_btn.setVisible(true);
    }                                              

    private void formel_Blogg_btnMousePressed(java.awt.event.MouseEvent evt) {                                              
        formel_Blogg_btn.setBackground(clickedColorBtn);
        formel_Blogg_btn.setVisible(false);
        formel_Blogg_btn.setVisible(true);
    }                                             

    private void informell_Blogg_btnMousePressed(java.awt.event.MouseEvent evt) {                                                 
        informell_Blogg_btn.setBackground(clickedColorBtn);
        informell_Blogg_btn.setVisible(false);
        informell_Blogg_btn.setVisible(true);
    }                                                

    private void informell_Blogg_btnMouseReleased(java.awt.event.MouseEvent evt) {                                                  
        informell_Blogg_btn.setBackground(hoverColorBtn);
        informell_Blogg_btn.setVisible(false);
        informell_Blogg_btn.setVisible(true);
    }                                                 

    private void projects_btnMousePressed(java.awt.event.MouseEvent evt) {                                          
        projects_btn.setBackground(clickedColorBtn);
        projects_btn.setVisible(false);
        projects_btn.setVisible(true);
    }                                         

    private void projects_btnMouseReleased(java.awt.event.MouseEvent evt) {                                           
        projects_btn.setBackground(hoverColorBtn);
        projects_btn.setVisible(false);
        projects_btn.setVisible(true);
    }                                          

    private void notis_btnMousePressed(java.awt.event.MouseEvent evt) {                                       
        notis_btn.setBackground(clickedColorBtn);
        notis_btn.setVisible(false);
        notis_btn.setVisible(true);
    }                                      

    private void notis_btnMouseReleased(java.awt.event.MouseEvent evt) {                                        
        notis_btn.setBackground(hoverColorBtn);
        notis_btn.setVisible(false);
        notis_btn.setVisible(true);
    }                                       

    private void account_btnMousePressed(java.awt.event.MouseEvent evt) {                                         
        account_btn.setBackground(clickedColorBtn);
        account_btn.setVisible(false);
        account_btn.setVisible(true);
        
    }                                        

    private void account_btnMouseReleased(java.awt.event.MouseEvent evt) {                                          
        account_btn.setBackground(hoverColorBtn);
        account_btn.setVisible(false);
        account_btn.setVisible(true);
    }                                         
    //En klick funktion, i dem här ska alla länkar till andra metoder och klasser ligga
    private void formel_Blogg_btnMouseClicked(java.awt.event.MouseEvent evt) {                                              
        
        
    }                                             
    //klick Funktion
    private void informell_Blogg_btnMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        
       
    }                                                

    private void account_btnMouseClicked(java.awt.event.MouseEvent evt) {                                         
        
        
    }                                        

    private void projects_btnMouseClicked(java.awt.event.MouseEvent evt) {                                          
       
    }                                         

    private void formBlg_LblMouseClicked(java.awt.event.MouseEvent evt) {                                         
         System.out.println("Formella");
         
         Blogg inlagg = new Blogg(this.minDatabaskoppling, 5);
        ArrayList<HashMap<String, String>> inlaggen = inlagg.hamtaFormellaBloggInlagg();
        ArrayList<HashMap<String, String>> formellaBloggInlaggMedAnvandare = inlagg.hamtaBloggInlaggMedAnvandare(inlaggen);
        
        jPanel1.removeAll();
        
        //jScrollPane1.getViewport().add(tabellen, null);
        javax.swing.JLabel hej = new JLabel();
        hej.setText("Här visas alla formella inlägg");
        jPanel1.add(hej, null);
        for(int i =0; i < formellaBloggInlaggMedAnvandare.size(); i++){
            
            // hämta kommentarer till blog
            ArrayList kommentarer = new Kommentar(minDatabaskoppling)
                    .hamtaKommentarerTillBlogg(Integer.parseInt(formellaBloggInlaggMedAnvandare.get(i).get("ID")));
 
            hej = new JLabel();
            javax.swing.JLabel hej2 = new JLabel();
            ettInlagg ettInlagg1 = new ettInlagg( this.minDatabaskoppling, formellaBloggInlaggMedAnvandare.get(i), 1, kommentarer);
            
            //ettInlagg1.setPost();
            hej.setText(ettInlagg1.getRubrik());
            hej2.setText(ettInlagg1.getSkapad());
            
            JButton btn = ettInlagg1.getButton();
            
            jPanel1.add(hej, null);
            jPanel1.add(hej2, null);
            jPanel1.add(btn, null);
            
            
        }
        // uppdatera jframe
        //frame.setVisible(true);
        //GridLayout boxlayout = new GridLayout(0,1);
        //jPanel1.setLayout(boxlayout);
        /*JScrollPane panelPane = new JScrollPane(panel, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);*/
        //jPanel1.add(panel);
        
       SwingUtilities.updateComponentTreeUI(this);
         
    }                                        

    private void informBlg_LblMouseClicked(java.awt.event.MouseEvent evt) {                                           
        
        Blogg inlagg = new Blogg(this.minDatabaskoppling, 5);
        ArrayList<HashMap<String, String>> inlaggen = inlagg.hamtaInformellaBloggInlagg();
        ArrayList<HashMap<String, String>> formellaBloggInlaggMedAnvandare = inlagg.hamtaBloggInlaggMedAnvandare(inlaggen);
        
        jPanel1.removeAll();
        
        //jScrollPane1.getViewport().add(tabellen, null);
        javax.swing.JLabel hej = new JLabel();
        hej.setText("Här visas alla formella inlägg");
        jPanel1.add(hej, null);
        for(int i =0; i < formellaBloggInlaggMedAnvandare.size(); i++){
            
            // hämta kommentarer till blog
            ArrayList kommentarer = new Kommentar(minDatabaskoppling)
                    .hamtaKommentarerTillBlogg(Integer.parseInt(formellaBloggInlaggMedAnvandare.get(i).get("ID")));
 
            hej = new JLabel();
            javax.swing.JLabel hej2 = new JLabel();
            ettInlagg ettInlagg1 = new ettInlagg( this.minDatabaskoppling, formellaBloggInlaggMedAnvandare.get(i), 1, kommentarer);
            
            //ettInlagg1.setPost();
            hej.setText(ettInlagg1.getRubrik());
            hej2.setText(ettInlagg1.getSkapad());
            
            JButton btn = ettInlagg1.getButton();
            
            jPanel1.add(hej, null);
            jPanel1.add(hej2, null);
            jPanel1.add(btn, null);
            
            
        }
        javax.swing.JLabel hej1 = new JLabel();
        hej1.setText("---");
        jPanel1.add(hej1, null);
        // uppdatera jframe
        //frame.setVisible(true);
        //GridLayout boxlayout = new GridLayout(0,1);
        //jPanel1.setLayout(boxlayout);
        /*JScrollPane panelPane = new JScrollPane(panel, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);*/
        //jPanel1.add(panel);
        
       SwingUtilities.updateComponentTreeUI(this);
        
    }                                          

    private void projBtn_LblMouseClicked(java.awt.event.MouseEvent evt) {                                         
        
        System.out.println("Projet");
        
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jPanel1.removeAll();
        Anvandare obj1 = new Anvandare(minDatabaskoppling, this.anvandareID, 1);
        HashMap<String, Boolean> installningar = new HashMap<String, Boolean>();
        installningar.put("bloggnotis", true);
        installningar.put("kommentarer", true);
        installningar.put("bloggtags", true);
        ArrayList<HashMap<String, String>> res = obj1.anvandarSidan(installningar);
        System.out.println(res);
        
        javax.swing.JLabel hej = new JLabel();
        for(int i =0; i < res.size(); i++){
            
 
            hej = new JLabel();
            javax.swing.JLabel hej2 = new JLabel();
            javax.swing.JLabel hej3 = new JLabel();
            javax.swing.JLabel hej4 = new JLabel();
            ettInlagg ettInlagg1 = new ettInlagg( this.minDatabaskoppling, res.get(i), 1);
            
            
            //ettInlagg1.setPost();
            hej4.setText(ettInlagg1.getTyp());
            hej.setText(ettInlagg1.getRubrik());
            hej2.setText(ettInlagg1.getSkapad());
            hej3.setText(ettInlagg1.getKommentar());
            
            JButton btn = ettInlagg1.getButton();
            
            jPanel1.add(hej4, null);
            jPanel1.add(hej, null);
            jPanel1.add(hej2, null);
            jPanel1.add(hej3, null);
            if(btn != null){
            jPanel1.add(btn, null);
            }
            
            
        }
        
        
        javax.swing.JLabel hej1 = new JLabel();
        hej1.setText("----");
        jPanel1.add(hej1, null);
        SwingUtilities.updateComponentTreeUI(this);
        
    }                                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Page(minDatabaskoppling, 3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel account_btn;
    private javax.swing.JLabel account_lbl;
    private javax.swing.JLabel formBlg_Lbl;
    private javax.swing.JPanel formel_Blogg_btn;
    private javax.swing.JLabel informBlg_Lbl;
    private javax.swing.JPanel informell_Blogg_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel newsflow_Panel;
    private javax.swing.JPanel notis_btn;
    private javax.swing.JLabel notis_lbl;
    private javax.swing.JLabel projBtn_Lbl;
    private javax.swing.JPanel projects_btn;
    // End of variables declaration                   

    private Color hoverColorBtn = new Color(41, 205, 255, 200);
    private Color baseColorBtn = new Color(3, 194, 252, 150);
    private Color clickedColorBtn = new Color(117, 223, 255, 200);
    //Initierar alla delar av huvud UI
    public void initMainWindow()
    {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        formel_Blogg_btn.setBackground(baseColorBtn);
        
        informell_Blogg_btn.setBackground(baseColorBtn);
        
        projects_btn.setBackground(baseColorBtn);
        
        
        
        newsflow_Panel.setBackground(baseColorBtn);
        
        
        
       
        
        notis_btn.setBackground(baseColorBtn);
        
        account_btn.setBackground(baseColorBtn);
        
      
        
        System.out.println("Init of Main Page Complete");    
    };
}
