/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronaprojekt;

import static coronaprojekt.Main_Page.minDatabaskoppling;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.awt.*; 

/**
 *
 * @author Jacob
 */
public class ny_main_page extends javax.swing.JFrame {

    public static InfDB minDatabaskoppling;
public static int anvandareID;
public String kategori = "";
    
    public ny_main_page(InfDB minDatabaskoppling, int anvandareID) {
        initComponents();
        //initMainWindow();
        this.minDatabaskoppling = minDatabaskoppling;
        this.anvandareID = anvandareID;
    
    Blogg nyBloggKlass = new Blogg(minDatabaskoppling, 10);
    jComboBox1.removeAllItems();
    nyBloggKlass.valjKategori(jComboBox1);
    
    this.setExtendedState(this.MAXIMIZED_BOTH);
    //jPanel1.setExtendedState(jPanel1.MAXIMIZED_BOTH);

    
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Formella blogg inlägg");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formBlg_LblMouseClicked(evt);
            }
        });

        jButton2.setText("Informella blogg inlägg");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informBlg_LblMouseClicked(evt);
            }
        });

        jButton3.setText("Skapa projekt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mitt nyhetsflöde");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton5.setText("Skapa blogg inlägg");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Stäng av/på notiser");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Boka möte");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Se mina möten");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(10, 1, 5, 5));

        jButton9.setText("Svara på möte");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextField1.setText("MoteID");

        jButton10.setText("Stäng projekt");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Välj notis");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formBlg_LblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formBlg_LblMouseClicked
        System.out.println("Formella");
         jPanel1.removeAll();
         Blogg inlagg = new Blogg(this.minDatabaskoppling, 5);
         ArrayList<HashMap<String, String>> inlaggen = new ArrayList<>();
         if(this.kategori.length() > 0){
             inlaggen = inlagg.hamtaFormellaBloggInlaggMedKategori(this.kategori);
         }else{
            inlaggen = inlagg.hamtaFormellaBloggInlagg();
         }
         
         javax.swing.JPanel nypanel = new JPanel();
         nypanel.setLayout(new GridLayout(0, 1));
         
         if(inlaggen != null && inlaggen.size() > 0){
        ArrayList<HashMap<String, String>> formellaBloggInlaggMedAnvandare = inlagg.hamtaBloggInlaggMedAnvandare(inlaggen);
        
        
        
        //jScrollPane1.getViewport().add(tabellen, null);
        javax.swing.JLabel hej = new JLabel();
        hej.setText("Här visas alla formella inlägg");
        nypanel.add(hej, null);
        for(int i =0; i < formellaBloggInlaggMedAnvandare.size(); i++){
            
            // hämta kommentarer till blog
            ArrayList kommentarer = new Kommentar(minDatabaskoppling)
                    .hamtaKommentarerTillBlogg(Integer.parseInt(formellaBloggInlaggMedAnvandare.get(i).get("ID")));
 
            hej = new JLabel();
            javax.swing.JLabel hej2 = new JLabel();
            ettInlagg ettInlagg1 = new ettInlagg( this.minDatabaskoppling, formellaBloggInlaggMedAnvandare.get(i), 1, kommentarer);
            
            //ettInlagg1.setPost();
            hej.setText(ettInlagg1.getRubrik());
            hej2.setText(ettInlagg1.getSkapad());
            
            JButton btn = ettInlagg1.getButton();
            
            nypanel.add(hej, null);
            nypanel.add(hej2, null);
            nypanel.add(btn, null);
            
            
        }
        // uppdatera jframe
        //frame.setVisible(true);
        //GridLayout boxlayout = new GridLayout(0,1);
        //jPanel1.setLayout(boxlayout);
        /*JScrollPane panelPane = new JScrollPane(panel, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);*/
        //jPanel1.add(panel);
        
       
         }else{
             javax.swing.JLabel hej2 = new JLabel();
             hej2.setText("Fanns inga artiklar");
             nypanel.add(hej2, null);
         }
         jPanel1.add(nypanel, null);
         SwingUtilities.updateComponentTreeUI(this);

    }//GEN-LAST:event_formBlg_LblMouseClicked

    private void informBlg_LblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informBlg_LblMouseClicked
        System.out.println("Informella");
        jPanel1.removeAll();
         Blogg inlagg = new Blogg(this.minDatabaskoppling, 5);
         ArrayList<HashMap<String, String>> inlaggen = new ArrayList<>();
         if(this.kategori.length() > 0){
             inlaggen = inlagg.hamtaInformellaBloggInlaggMedKategori(this.kategori);
         }else{
            inlaggen = inlagg.hamtaFormellaBloggInlagg();
         }
         
         javax.swing.JPanel nypanel = new JPanel();
         nypanel.setLayout(new GridLayout(0, 1));
         
         if(inlaggen != null && inlaggen.size() > 0){
        ArrayList<HashMap<String, String>> formellaBloggInlaggMedAnvandare = inlagg.hamtaBloggInlaggMedAnvandare(inlaggen);
        
        
        
        //jScrollPane1.getViewport().add(tabellen, null);
        javax.swing.JLabel hej = new JLabel();
        hej.setText("Här visas alla Informella inlägg");
        nypanel.add(hej, null);
        for(int i =0; i < formellaBloggInlaggMedAnvandare.size(); i++){
            
            // hämta kommentarer till blog
            ArrayList kommentarer = new Kommentar(minDatabaskoppling)
                    .hamtaKommentarerTillBlogg(Integer.parseInt(formellaBloggInlaggMedAnvandare.get(i).get("ID")));
 
            hej = new JLabel();
            javax.swing.JLabel hej2 = new JLabel();
            ettInlagg ettInlagg1 = new ettInlagg( this.minDatabaskoppling, formellaBloggInlaggMedAnvandare.get(i), 1, kommentarer);
            
            //ettInlagg1.setPost();
            hej.setText(ettInlagg1.getRubrik());
            hej2.setText(ettInlagg1.getSkapad());
            
            JButton btn = ettInlagg1.getButton();
            
            nypanel.add(hej, null);
            nypanel.add(hej2, null);
            nypanel.add(btn, null);
            
            
        }
        // uppdatera jframe
        //frame.setVisible(true);
        //GridLayout boxlayout = new GridLayout(0,1);
        //jPanel1.setLayout(boxlayout);
        /*JScrollPane panelPane = new JScrollPane(panel, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
            JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);*/
        //jPanel1.add(panel);
        
       
         }else{
             javax.swing.JLabel hej2 = new JLabel();
             hej2.setText("Fanns inga artiklar");
             nypanel.add(hej2, null);
         }
         jPanel1.add(nypanel, null);
 SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_informBlg_LblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.removeAll();
        Anvandare obj1 = new Anvandare(minDatabaskoppling, this.anvandareID, 1);
        HashMap<String, Boolean> installningar = new HashMap<String, Boolean>();
        installningar.put("bloggnotis", true);
        installningar.put("kommentarer", true);
        installningar.put("bloggtags", true);
        ArrayList<HashMap<String, String>> res = obj1.anvandarSidan(installningar);
        System.out.println(res);
        
         javax.swing.JPanel nypanel = new JPanel();
         nypanel.setLayout(new GridLayout(0, 1));
        
        javax.swing.JLabel hej = new JLabel();
        for(int i =0; i < res.size(); i++){
            
 
            hej = new JLabel();
            javax.swing.JLabel hej2 = new JLabel();
            javax.swing.JLabel hej3 = new JLabel();
            javax.swing.JLabel hej4 = new JLabel();
            ettInlagg ettInlagg1 = new ettInlagg( this.minDatabaskoppling, res.get(i), 1);
            
            
            //ettInlagg1.setPost();
            hej4.setText(ettInlagg1.getTyp());
            hej.setText(ettInlagg1.getRubrik());
            hej2.setText(ettInlagg1.getSkapad());
            hej3.setText(ettInlagg1.getKommentar());
            
            JButton btn = ettInlagg1.getButton();
            
            nypanel.add(hej4, null);
            nypanel.add(hej, null);
            nypanel.add(hej2, null);
            nypanel.add(hej3, null);
            if(btn != null){
            nypanel.add(btn, null);
            }
            
            
        }
        
        
        javax.swing.JLabel hej1 = new JLabel();
        hej1.setText("----");
        nypanel.add(hej1, null);
        jPanel1.add(nypanel, null);
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        System.out.println(jComboBox1.getSelectedItem());
        
        if(jComboBox1.getSelectedItem() != null){
        this.kategori = jComboBox1.getSelectedItem().toString();
        }
       
        System.out.println(this.kategori);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new SkapaBlogginlagg(minDatabaskoppling,
        this.anvandareID,
        "test").setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Login_Page user = new Login_Page(minDatabaskoppling);
        Object[] options = {"Ja", "Nej"};
        String res = "";
        String query = "";
        int reply = JOptionPane.showOptionDialog(
            null,
            "Vill du ha notiser?",
            "An Inane Question",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]);
        try {
                query = "select ID from Anvandare where Anvandarnamn ='" + user.getCurrentUserName() + "';";
                res = minDatabaskoppling.fetchSingle(query);
            } catch (InfException undantag) {
                System.out.println("Fel: " + undantag.getMessage());
            }
        int ID = Integer.parseInt(res); 
        if(reply == JOptionPane.YES_OPTION){
                        
            String fraga = "update NOTIS set EMAIL = 'J' where AGARE = " + ID;
            try {
                minDatabaskoppling.update(fraga);
                System.out.println("You're in");
            } catch (InfException ex) {
                Logger.getLogger(Main_Page.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("SUPERFEL");
            }
            
            JOptionPane.showMessageDialog(null, "Du har aktiverat notiser.");
        }
        else {
            String fraga = "update NOTIS set EMAIL = 'N' where AGARE = " +
                    ID + ";";
            
            try {
                minDatabaskoppling.update(fraga);
            } catch (InfException ex) {
                Logger.getLogger(Main_Page.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Du har stängt av notiser.");
        }  
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       new KallaTillMote(minDatabaskoppling,
        this.anvandareID).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new KalenderGUI(minDatabaskoppling,
        this.anvandareID).setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(jTextField1.getText().length() > 0){
        try{
            String fraga = "SELECT TITLE FROM MOTE WHERE ID = " + jTextField1.getText();
            String res = this.minDatabaskoppling.fetchSingle(fraga);
            new SvaraPaMote(minDatabaskoppling,
        this.anvandareID, res).setVisible(true);
        
        }catch(InfException e){
            
        }
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            new SkapaProjekt(minDatabaskoppling,
        this.anvandareID).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new StangaProjekt(minDatabaskoppling,
        this.anvandareID).setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       new ValjNotis(minDatabaskoppling).setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed
                                                                          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
