package coronaprojekt;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alice
 */
public class SkapaProjekt extends javax.swing.JFrame {
    
       private static InfDB minDatabaskoppling;
    private int anvandareID;

    /**
     * Creates new form SkapaProjekt
     */
    public SkapaProjekt(InfDB minDatabaskoppling) {
        initComponents();
        SkapaProjekt.minDatabaskoppling = minDatabaskoppling;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnJa = new javax.swing.JRadioButton();
        rbtnNej = new javax.swing.JRadioButton();
        fieldNamn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSkapa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbtnJa.setText("Ja");

        rbtnNej.setText("Nej");

        fieldNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamnActionPerformed(evt);
            }
        });

        jLabel1.setText("Namn :");

        btnSkapa.setText("Skapa");
        btnSkapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaActionPerformed(evt);
            }
        });

        jLabel2.setText("Publik :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSkapa)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnJa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnNej))
                    .addComponent(fieldNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbtnJa)
                    .addComponent(rbtnNej))
                .addGap(30, 30, 30)
                .addComponent(btnSkapa)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamnActionPerformed

    private void btnSkapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaActionPerformed
        // TODO add your handling code here:
        String anvNamn = fieldNamn.getText();
        int anv;
        String datum = "";

        if (rbtnJa.isSelected()) {
            try {

                int pId = Integer.parseInt(minDatabaskoppling.getAutoIncrement("FORSKNINGSPROJEKT", "ID"));
                Login_Page namn = new Login_Page(minDatabaskoppling);
                //Oskäker om denna metod fungerar, vet att det ska finnas en fungerade metod för detta
                anv = namn.getUserID();

              
                // Kan vi ha "hej" i konstruktorn???
                SkapaBlogginlagg d = new SkapaBlogginlagg(minDatabaskoppling, anv, "hej");
                datum = d.getCurrentDateTime();

                String publik = "UPDATE FORSKNINGSPROJEKT SET 'J' WHERE ID = " + pId;

                minDatabaskoppling.insert("INSERT INTO FORSKNINGSPROJEKT (ID, PUBLIK, NAMN, SKAPAD, SKAPARE) VALUES ('"+pId+"', '"+publik+"', '"+anvNamn+"', '"+datum+"', '"+anv+"')");
                    
                                JOptionPane.showMessageDialog(null, "Projektet är skapat!");

                
                
            } catch (InfException e) {

                System.out.println(e);
                System.out.println("Fel yao");

            }

        }
        
        if(rbtnNej.isSelected()){
        
        try {

                int pId = Integer.parseInt(minDatabaskoppling.getAutoIncrement("FORSKNINGSPROJEKT", "ID"));
                Login_Page namn = new Login_Page(minDatabaskoppling);
                //Oskäker om denna metod fungerar, vet att det ska finnas en fungerade metod för detta
                anv = namn.getUserID();

                
                // Kan vi ha "hej" i konstruktorn???
                SkapaBlogginlagg d = new SkapaBlogginlagg(minDatabaskoppling, anv, "hej");
                datum = d.getCurrentDateTime();

                String publik = "UPDATE FORSKNINGSPROJEKT SET 'N' WHERE ID = " + pId;

                minDatabaskoppling.insert("INSERT INTO FORSKNINGSPROJEKT (ID, PUBLIK, NAMN, SKAPAD, SKAPARE) VALUES ('"+pId+"', '"+publik+"', '"+anvNamn+"', '"+datum+"', '"+anv+"')");
                   
                JOptionPane.showMessageDialog(null, "Projektet är skapat!");
                
                
            } catch (InfException e) {

                System.out.println(e);
                System.out.println("Fel yao");

            }
        
        
        
        }
        
    }//GEN-LAST:event_btnSkapaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkapaProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkapaProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkapaProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkapaProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkapaProjekt(minDatabaskoppling).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkapa;
    private javax.swing.JTextField fieldNamn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtnJa;
    private javax.swing.JRadioButton rbtnNej;
    // End of variables declaration//GEN-END:variables
}
